### ISSUE TITLE
Function "Search" not working on "Compare two lists" (WINDOWS)

### ISSUE THREAD

**Issue by SrReykh** [KarboXXX/backosu#5]
# When you select the search option, the file path doesn't show
![image](https://user-images.githubusercontent.com/61100185/175837705-bbfadc75-04ba-4296-9a33-244a30927d8e.png)

# And the primary local disk is not shown, only "ROOT"

**Comment by KarboXXX** [comment]
Well, on Linux the root folder is shown, but the **Search** option only works when building from source and running from `npm start` from some weird reason. Thanks for the report, i'll be working to solve this issue!

**Comment by KarboXXX** [comment]
Fixed on [v2.3](https://github.com/KarboXXX/backosu/releases/tag/v2.3)
